controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute

# API Routes
authors_list:
    path: /api/authors
    controller: App\Controller\AuthorApiController::list
    methods: GET|HEAD

authors_show:
    path: /api/authors/{id}
    controller: App\Controller\AuthorApiController::show
    methods: GET|HEAD
    requirements:
        id: '[1-9][0-9]*'

genres_list:
    path: /api/genres
    controller: App\Controller\GenreApiController::list
    methods: GET|HEAD

genres_show:
    path: /api/genres/{id}
    controller: App\Controller\GenreApiController::show
    methods: GET|HEAD
    requirements:
        id: '[1-9][0-9]*'
